# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIjrTkwJbQq9hyPVDCZszCulV5Yidz3z
"""

import pandas as pd
import hashlib
import random
import logging
from datetime import datetime
from collections import Counter
random.seed(42)
logging.basicConfig(level=logging.INFO,format="%(asctime)s - %(message)s")
logging.info("Program started")
data={"Name":["Amit Sharma","Riya Verma","Kunal Singh","Neha Patel","Rahul Iyer","Pooja Mehta","Suresh Rao","Anjali Nair","Vikas Gupta","Snehal Joshi",
"Rohit Malhotra","Priya Khanna","Arjun Kapoor","Nitin Agarwal","Swati Mishra","Deepak Yadav","Manish Jain","Kavita Shah","Sanjay Kulkarni","Reema Banerjee",
"Harsh Vardhan","Isha Arora","Akash Tiwari","Meenal Gokhale","Varun Bansal","Shreya Chatterjee","Abhishek Pandey","Ritu Saxena","Mohit Bhatia","Tanvi Kulkarni",
"Ayush Srivastava","Pallavi Deshpande","Naveen Reddy","Shruti Pillai","Gaurav Chauhan","Rashmi Patil","Karthik Subramanian","Divya Malhotra","Pranav Kulkarni","Anita Fernandes",
"Siddharth Roy","Pankaj Tripathi","Sunita Verma","Alok Sinha","Nisha Kapoor","Vivek Anand","Preeti Arora","Sameer Khan","Bhavya Doshi","Ramesh Pillai"],
"Aadhaar":[str(100000000000+i) for i in range(50)],
"Age":[22,25,28,31,34,37,40,43,46,49,23,26,29,32,35,38,41,44,47,50,24,27,30,33,36,39,42,45,48,51,21,28,34,40,46,52,26,31,37,43,29,35,41,47,53,24,32,38,44,50],
"City":["Delhi","Mumbai","Bengaluru","Ahmedabad","Chennai","Pune","Hyderabad","Kochi","Jaipur","Indore",
"Noida","Gurgaon","Faridabad","Ghaziabad","Lucknow","Kanpur","Patna","Ranchi","Kolkata","Howrah",
"Bhubaneswar","Cuttack","Raipur","Bilaspur","Nagpur","Amravati","Nashik","Aurangabad","Solapur","Satara",
"Kolhapur","Sangli","Belgaum","Hubli","Dharwad","Mysuru","Udupi","Mangaluru","Manipal","Kasaragod",
"Trivandrum","Alappuzha","Kottayam","Thrissur","Palakkad","Coimbatore","Madurai","Salem","Erode","Tiruppur"],
"Salary":[28000,32000,36564,47894,44145,48142,52145,56564,60000,64568,
30450,34000,38889,41778,46445,50000,54142,58785,62456,66540,
31450,35050,39874,43235,47963,51852,55423,59123,63994,67846,
27234,33000,47000,53000,61065,69874,33631,41025,49746,57895,
35431,43097,51956,59567,67234,38000,39300,47540,55250,63056]}
df=pd.DataFrame(data)
print("Original Dataset\n",df)
print("\nTotal Records:",len(df))
print("Columns:",list(df.columns))
print("Missing Values:\n",df.isnull().sum())
df = df.drop(columns=["Name"])
def mask_aadhaar(aadhaar):
    return aadhaar[:8] + "XXXX"

df["Aadhaar"] = df["Aadhaar"].apply(mask_aadhaar)
def convert_age_to_group(age):
    if age<25:return"18-24"
    elif age<35:return"25-34"
    elif age<45:return"35-44"
    elif age<55:return"45-54"
    else:return"55+"
df["Age"]=df["Age"].apply(convert_age_to_group)
def mask_salary(salary):
    noise=random.randint(-1000,1000)
    return"₹"+str(salary+noise)[:2]+"XXX"
df["Salary"]=df["Salary"].apply(mask_salary)
SALT="india_privacy_2025"
def anonymize_city(city):
    return hashlib.sha256((city+SALT).encode()).hexdigest()[:7]
df["City"]=df["City"].apply(anonymize_city)
def calculate_k_anonymity(dataframe):
    return dataframe.groupby(["Age","City"]).size().min()
k_value=calculate_k_anonymity(df)
def evaluate_privacy(k):
    if k>=5:return"High Privacy"
    elif k>=3:return"Moderate Privacy"
    else:return"Low Privacy"
print("\nAge Group Distribution\n",Counter(df["Age"]))
print("\nAudit Timestamp:",datetime.now())
print("Records Processed:",len(df))
print("\nAnonymized Dataset\n",df)
print("\nK-Anonymity Level:",k_value)
print("Privacy Strength:",evaluate_privacy(k_value))
logging.info("Program completed successfully")